### ISSUE TITLE
Maven Dependency not found

### ISSUE THREAD

**Issue by lukethomas1** [daniel-shuy/kafka-protobuf-serde#1]
I can't find the package in any common Maven repo, I found [this](https://mvnrepository.com/artifact/com.github.daniel-shuy) but it doesn't have this project. I just copied the code for now but thought you'd like to know.

**Comment by daniel-shuy** [comment]
Thanks! I was facing an issue with GitHub previously (https://githubengineering.com/crypto-deprecation-notice/), which prevented me from executing the maven-release-plugin (which needs to push to GIT), then I got really busy and totally forgot that I haven't actually uploaded the artifacts to Maven Central.

I've released it now.
